// <auto-generated />
using System;
using Hotel_Sunrise.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hotel_Sunrise.Migrations
{
    [DbContext(typeof(Hotel_SunriseContext))]
    [Migration("20190903225406_Paises")]
    partial class Paises
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hotel_Sunrise.Models.Apps_Countries", b =>
                {
                    b.Property<int>("Apps_CountriesId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("country_code");

                    b.Property<string>("country_name");

                    b.HasKey("Apps_CountriesId");

                    b.ToTable("Apps_Countries");
                });

            modelBuilder.Entity("Hotel_Sunrise.Models.Clientes", b =>
                {
                    b.Property<int>("ClientesId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired();

                    b.Property<string>("Apps_CountriesId");

                    b.Property<string>("Direccion");

                    b.Property<string>("Identificacion")
                        .IsRequired();

                    b.Property<DateTime>("Modificado");

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.Property<string>("Telefono");

                    b.Property<string>("TipoIdentificacion")
                        .IsRequired();

                    b.Property<int>("UsuarioId");

                    b.HasKey("ClientesId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Hotel_Sunrise.Models.DetalleReservacion", b =>
                {
                    b.Property<int>("DetalleReservacionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad");

                    b.Property<int>("HabitacionId");

                    b.Property<int>("ReservacionId");

                    b.HasKey("DetalleReservacionId");

                    b.HasIndex("HabitacionId");

                    b.HasIndex("ReservacionId");

                    b.ToTable("DetalleReservacion");
                });

            modelBuilder.Entity("Hotel_Sunrise.Models.Habitacion", b =>
                {
                    b.Property<int>("HabitacionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AsignarReservacionId");

                    b.Property<string>("Estado");

                    b.Property<DateTime>("Modificado");

                    b.Property<int>("No_Habitacion");

                    b.Property<int>("TipoId");

                    b.Property<int>("UsuarioId");

                    b.HasKey("HabitacionId");

                    b.HasIndex("TipoId");

                    b.ToTable("Habitacion");
                });

            modelBuilder.Entity("Hotel_Sunrise.Models.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Estado_fact");

                    b.Property<decimal>("IVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReservacionId");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo_Pago");

                    b.Property<decimal>("TotalPagar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PagoId");

                    b.HasIndex("ReservacionId");

                    b.ToTable("Pago");
                });

            modelBuilder.Entity("Hotel_Sunrise.Models.Reservacion", b =>
                {
                    b.Property<int>("ReservacionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientesId");

                    b.Property<int>("Dias");

                    b.Property<bool>("Estado");

                    b.Property<DateTime>("Fecha");

                    b.Property<DateTime>("Fecha_Ingreso");

                    b.Property<DateTime>("Modificado");

                    b.Property<string>("Observaciones")
                        .IsRequired();

                    b.Property<int>("UsuarioId");

                    b.HasKey("ReservacionId");

                    b.HasIndex("ClientesId");

                    b.ToTable("Reservacion");
                });

            modelBuilder.Entity("Hotel_Sunrise.Models.TipoH", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion");

                    b.Property<DateTime>("Modificado");

                    b.Property<decimal>("T_Noche")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Tarifa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId");

                    b.HasKey("TipoId");

                    b.ToTable("TipoH");
                });

            modelBuilder.Entity("Hotel_Sunrise.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre");

                    b.Property<string>("Turno");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Hotel_Sunrise.Models.DetalleReservacion", b =>
                {
                    b.HasOne("Hotel_Sunrise.Models.Habitacion", "Habitacion")
                        .WithMany()
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hotel_Sunrise.Models.Reservacion", "Reservacion")
                        .WithMany("DetalleReservacions")
                        .HasForeignKey("ReservacionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hotel_Sunrise.Models.Habitacion", b =>
                {
                    b.HasOne("Hotel_Sunrise.Models.TipoH", "Tipo")
                        .WithMany("Habitaciones")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hotel_Sunrise.Models.Pago", b =>
                {
                    b.HasOne("Hotel_Sunrise.Models.Reservacion", "Reservacion")
                        .WithMany()
                        .HasForeignKey("ReservacionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hotel_Sunrise.Models.Reservacion", b =>
                {
                    b.HasOne("Hotel_Sunrise.Models.Clientes", "Cliente")
                        .WithMany("Reservaciones")
                        .HasForeignKey("ClientesId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
